name: flutterdemo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化
  flutter_localizations:
    sdk: flutter
  source_gen: ^0.9.4+1
  annotation_route: ^0.0.2
#  fish_redux: ^0.1.3
  grpc: ^1.0.1
  protobuf: ^0.13.4
  http: ^0.12.0+2
  analyzer: any
  #国际化加翻译
  intl: ^0.16.0
  #webview
#  webview_flutter: ^0.3.14+1
  webview_flutter:
    git:
      url: https://github.com/songshitong/flutter-plugins.git
      path: packages/webview_flutter
      ref: develop
#  webview_flutter:
#    path: /Users/issmac/FlutterWorkspace/flutter-plugins/packages/webview_flutter
  #视频播放
  video_player: ^0.10.0+8
  #android intent
  android_intent: ^0.3.0+2
  #使用URL拉起
  url_launcher: ^5.2.0
  gif_ani: ^0.0.2
  #image解析
  image: ^2.1.4
  # ffmpeg
  flutter_ffmpeg: ^0.2.7
  #image picker
  image_picker: ^0.6.0+17
  # 音频录制，播放
  flutter_sound: ^1.5.1

  w_reorder_list: ^0.1.0
  #高德地图
  amap_base_location: ^0.4.0+1
  # 阿里推送
  rammus: ^0.0.4
  #分享 shareSDK
  sharesdk: ^1.1.8
  #权限
  permission_handler: ^3.2.2
  #文件路径
  path_provider: ^1.4.0
  #数据共享
  provider: ^3.1.0+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2



dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^4.0.0
  build_runner: ^1.3.3
  intl_translation: ^0.17.4




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
     - lib/img/
     - lib/game/flappybird/hilo/
     - lib/game/flappybird/images/
     - lib/game/flappybird/src/
     - lib/game/flappybird/index.html



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
